export const styles = {
  container: 'w-full h-full rounded-lg overflow-hidden shadow-lg p-2 pt-4',
  header: 'w-full flex flex-row justify-between items-start px-4 py-2',
  left: 'w-5/6 flex flex-row justify-start items-center text-xl font-bold text-[#515DC3]',
  right: 'w-1/6 flex flex-row justify-end items-start',
  headerTitle: 'text-xl font-bold text-[#515DC3]',
  headerDescription: 'text-sm font-300 text-white',
  headerButton: 'w-1/6 flex flex-row justify-center items-center bg-white rounded-md',
  chart: 'w-full h-3/4 flex flex-col pl-10 pr-10 pt-4 pb-4',
  bitcoinContainer: 'flex flex-row justify-center items-center bg-[#F0F3F5] rounded-lg py-2 px-4',
  bitcoinText: 'text-s font-300 text-[#90A2B2] ml-2',
  buySellContainer: 'flex flex-col justify-between items-center ml-2',
  sellText: 'text-s font-300 text-[#F15757]',
  buyText: 'text-s font-300 text-[#5BAA4F]',
  sellContainer: 'flex flex-row justify-between items-center bg-[#F0F3F5] rounded-lg py-2 px-4 ml-2',
  chartHeaderContainer: 'w-full flex flex-row justify-start items-center mb-4',
  chartHeader: 'flex flex-row justify-start items-center mr-4',
  coloredCircle: 'w-4 h-2 rounded-lg bg-[#6979F8] mr-2',
  chartHeaderText: 'text-xs font-300 text-[#90A2B2]',
  chartContainer: 'w-full h-full flex flex-col justify-start items-start',
  chartTitle: 'text-xl font-bold text-[#515DC3]',
  chartDescription: 'text-sm font-300 text-white',
  chartButton: 'w-1/6 flex flex-row justify-center items-center bg-white rounded-md',
};